FROM centos:6.8

WORKDIR /home/tlbb

RUN yum install -y unixODBC.i686
COPY ./config/odbc.ini /etc/odbc.ini

RUN curl -L http://mirror.centos.org/centos/6/os/i386/Packages/mysql-connector-odbc-5.1.5r1144-7.el6.i686.rpm -o /tmp/mysql-connector-odbc-5.1.5r1144-7.el6.i686.rpm && \
    yum localinstall -y /tmp/mysql-connector-odbc-5.1.5r1144-7.el6.i686.rpm && \
    rm -f /tmp/mysql-connector-odbc-5.1.5r1144-7.el6.i686.rpm

CMD tail -f /dev/null

